# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from . import signup_ui
from . import bg_img_rc


class Ui_login_form(object):

    def __init__(self):
        self.login_form = QtWidgets.QDialog()
        self.signup_form = None
        self.MainWindow = None

    def open_signup_form(self):
        pass

    def open_main_form(self):
        pass

    def setupUi(self, login_form):
        login_form.setObjectName("login_form")
        login_form.resize(370, 570)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(login_form.sizePolicy().hasHeightForWidth())
        login_form.setSizePolicy(sizePolicy)
        login_form.setMinimumSize(QtCore.QSize(370, 570))
        login_form.setMaximumSize(QtCore.QSize(370, 570))
        login_form.setStyleSheet("background-color: rgb(136, 0, 0);")
        self.login_btn = QtWidgets.QPushButton(login_form)
        self.login_btn.setGeometry(QtCore.QRect(80, 440, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("QPushButton{\n"
                                     "    background-color: rgb(255, 255, 255);\n"
                                     "    color: rgb(136, 0, 0);\n"
                                     "    border-style: outset;\n"
                                     "    border-radius: 10px;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:hover{\n"
                                     "    background-color: rgb(249, 186, 187);\n"
                                     "}")
        self.login_btn.setObjectName("login_btn")
        self.create_acc_link = QtWidgets.QPushButton(login_form)
        self.create_acc_link.setGeometry(QtCore.QRect(212, 380, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        self.create_acc_link.setFont(font)
        self.create_acc_link.setStyleSheet("QPushButton {\n"
                                           "    border: 0px;\n"
                                           "    color: rgb(255, 255, 255);\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:hover {\n"
                                           "    \n"
                                           "    color: rgb(255, 255, 0);\n"
                                           "};")
        self.create_acc_link.setObjectName("create_acc_link")
        self.user_name_edit = QtWidgets.QLineEdit(login_form)
        self.user_name_edit.setGeometry(QtCore.QRect(30, 260, 310, 40))
        self.user_name_edit.setMinimumSize(QtCore.QSize(310, 40))
        self.user_name_edit.setMaximumSize(QtCore.QSize(310, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.user_name_edit.setFont(font)
        self.user_name_edit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.user_name_edit.setMaxLength(20)
        self.user_name_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.user_name_edit.setObjectName("user_name_edit")
        self.password_edit = QtWidgets.QLineEdit(login_form)
        self.password_edit.setGeometry(QtCore.QRect(30, 320, 310, 40))
        self.password_edit.setMinimumSize(QtCore.QSize(310, 40))
        self.password_edit.setMaximumSize(QtCore.QSize(310, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.password_edit.setFont(font)
        self.password_edit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password_edit.setMaxLength(16)
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.password_edit.setObjectName("password_edit")
        self.label = QtWidgets.QLabel(login_form)
        self.label.setGeometry(QtCore.QRect(70, 10, 241, 221))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/img/Barbershop/2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(login_form)
        QtCore.QMetaObject.connectSlotsByName(login_form)

    def retranslateUi(self, login_form):
        _translate = QtCore.QCoreApplication.translate
        login_form.setWindowTitle(_translate("login_form", "Đăng nhập"))
        self.login_btn.setText(_translate("login_form", "ĐĂNG NHẬP"))
        self.create_acc_link.setText(_translate("login_form", "Tạo tài khoản"))
        self.user_name_edit.setPlaceholderText(_translate("login_form", "Tên đăng nhập"))
        self.password_edit.setPlaceholderText(_translate("login_form", "Mật khẩu"))


